<?xml version="1.0"?>

<robot name="mobile_robot2" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="chassisHeight" value="0.1"/>
  <xacro:property name="chassisLength" value="0.4"/>
  <xacro:property name="chassisWidth" value="0.2"/>
  <xacro:property name="chassisMass" value="50"/>

  <xacro:property name="casterRadius" value="0.05"/>
  <xacro:property name="casterMass" value="5"/>

  <xacro:property name="wheelWidth" value="0.05"/>
  <xacro:property name="wheelRadius" value="0.1"/>
  <xacro:property name="wheelPos" value="0.2"/>
  <xacro:property name="wheelMass" value="5"/>

  <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.1"/>


  <xacro:include filename="$(find mobile_robot2_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find mobile_robot2_description)/urdf/macros.xacro" />

  <link name="footprint" />

  <joint name="base_joint" type="fixed">
    <parent link="footprint"/>
    <child link="chassis"/>
  </joint>

  <link name="chassis">
    <collision>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
	<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
	<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
    </inertial>
  </link>

  <joint name="fixed" type="fixed">
    <parent link="chassis"/>
    <child link="caster_wheel"/>
  </joint>

  <link name="caster_wheel">

    <collision>
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
	<sphere radius="${casterRadius}"/>
      </geometry>     
    </collision>
  
    <visual> 
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
	<sphere radius="${casterRadius}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <mass value="${casterMass}"/>
      <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
    </inertial>
  </link>


  <wheel lr="left" tY="-1"/>
  <wheel lr="right" tY="1"/>
  
  	<link name="SonarFront_frame">
        </link>
	<joint name="Sonar/Front_sensor_fixedjoint" type="fixed">
		<parent link="chassis"/>
		<child link="SonarFront_frame"/>
		<origin rpy="0 0.0 0" xyz="0.2 0 0.1"/>
	</joint>

  	<link name="SonarLeftFront_frame">
        </link>
	<joint name="Sonar/LeftFront_sensor_fixedjoint" type="fixed">
		<parent link="chassis"/>
		<child link="SonarLeftFront_frame"/>
		<origin rpy="0 0.0 1.57" xyz="-0.02 0.1 0.1"/>
	</joint>

  	<link name="SonarLeftBack_frame">
        </link>
	<joint name="Sonar/LeftBack_sensor_fixedjoint" type="fixed">
		<parent link="chassis"/>
		<child link="SonarLeftBack_frame"/>
		<origin rpy="0 0.0 1.57" xyz="-0.2 0.1 0.1"/>
	</joint>
        
  	<link name="SonarRightFront_frame">
        </link>
	<joint name="Sonar/RightFront_sensor_fixedjoint" type="fixed">
		<parent link="chassis"/>
		<child link="SonarRightFront_frame"/>
		<origin rpy="0 0.0 -1.57" xyz="-0.02 -0.1 0.1"/>
	</joint>        
  	<link name="SonarRightBack_frame">
        </link>
	<joint name="Sonar/RightBack_sensor_fixedjoint" type="fixed">
		<parent link="chassis"/>
		<child link="SonarRightBack_frame"/>
		<origin rpy="0 0.0 -1.57" xyz="-0.2 -0.1 0.1"/>
	</joint>        
        
    <joint name="imu_joint" type="fixed">
        <origin xyz="0 0 0"/>
        <parent link="chassis"/>
        <child link="imu_link"/>
    </joint>


    <link name="imu_link">
    </link>
        
        
    <xacro:include filename="$(find mobile_robot2_description)/urdf/mobile_robot2.gazebo" />
  
</robot>
